bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E034/E034_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E034/E034_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E034/E034_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E034/E034_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E034/E034_chr5_15_igv.bed E034
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E034/E034_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E037/E037_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E037/E037_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E037/E037_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E037/E037_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E037/E037_chr5_15_igv.bed E037
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E037/E037_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E038/E038_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E038/E038_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E038/E038_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E038/E038_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E038/E038_chr5_15_igv.bed E038
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E038/E038_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E039/E039_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E039/E039_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E039/E039_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E039/E039_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E039/E039_chr5_15_igv.bed E039
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E039/E039_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E040/E040_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E040/E040_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E040/E040_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E040/E040_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E040/E040_chr5_15_igv.bed E040
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E040/E040_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E041/E041_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E041/E041_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E041/E041_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E041/E041_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E041/E041_chr5_15_igv.bed E041
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E041/E041_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E042/E042_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E042/E042_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E042/E042_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E042/E042_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E042/E042_chr5_15_igv.bed E042
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E042/E042_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E043/E043_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E043/E043_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E043/E043_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E043/E043_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E043/E043_chr5_15_igv.bed E043
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E043/E043_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E044/E044_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E044/E044_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E044/E044_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E044/E044_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E044/E044_chr5_15_igv.bed E044
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E044/E044_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E045/E045_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E045/E045_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E045/E045_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E045/E045_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E045/E045_chr5_15_igv.bed E045
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E045/E045_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E047/E047_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E047/E047_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E047/E047_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E047/E047_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E047/E047_chr5_15_igv.bed E047
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E047/E047_chr5_15_igv.bed
bedtools intersect -a /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/segmentation/E048/E048_18_core_K27ac_segments.bed.gz -b /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/chr5_15_region.bed > /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E048/E048_chr5_15_segment.bed
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E048/E048_chr5_15_segment.bed
python /u/home/h/havu73/project-ernst/source/chromHMM_utilities/get_segmentation_file_with_color.py /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E048/E048_chr5_15_segment.bed.gz /u/home/h/havu73/project-ernst/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E048/E048_chr5_15_igv.bed E048
gzip /u/home/h/havu73/project-ernst/diff_pete/roadmap/raw_semgentation/blood/E048/E048_chr5_15_igv.bed
